name: Manually Deploy to Heroku

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Heroku CLI
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          docker_heroku_process_type: web
          stack: "container"
          region: "eu"
        env:
          HD_HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
          HD_HEROKU_APP_NAME: ${{secrets.HEROKU_APP_NAME}}

      - name: Deploy to Heroku Team
        run: |
          heroku apps:deploy --app ${{secrets.HEROKU_APP_NAME}} --team ${{secrets.HEROKU_TEAM_NAME}} --region eu
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
